---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
    - ""
    - apps
    - batch
    - extensions
    - policy
    - rbac.authorization.k8s.io
    resources:
    - persistentvolumeclaims
    - pods
    - services
    - replicationcontrollers
    - persistentvolumeclaims
    - persistentvolumes
    - endpoints
    - secrets
    - configmaps
    - serviceaccounts
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - statefulsets
    - statefulsets/scale
    - jobs
    verbs:
    - '*'

  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - podmonitors
    verbs:
    - '*'

  ##
  ## Rules for plugins.cloudminds.com/v1, Kind: Loki
  ##
  - apiGroups:
      - plugins.cloudminds.com
    resources:
      - lokis
      - lokis/status
      - lokis/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
