---
# tasks file for Loki
- name: Loki Operator | Loki | ConfigMap
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'loki.config.yaml') | from_yaml }}"

- include_tasks: redis.yaml
  when: '{{cacheconfig.type == "redis"}}'

- include_tasks: loki-frontend.yaml
  when: '{{service.mode == "cluster"}}'

- include_tasks: loki-gateway.yaml
  when: '{{service.mode == "cluster"}}'

- include_tasks: loki-system.yaml