apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    plugins.cloudminds.com/loki: loki-redis
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-redis'
  name: '{{ ansible_operator_meta.name }}-redis-conf'
  namespace: '{{ ansible_operator_meta.namespace }}'
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    tcp-keepalive 300
    loglevel notice
    databases 2
    save 900 1  
    save 300 10
    save 60 10000
    dir /var/lib/redis
    appendonly no
    maxmemory 858993459