apiVersion: v1
kind: Service
metadata:
  labels:
    plugins.cloudminds.com/loki: loki-redis
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-redis'
  name: '{{ ansible_operator_meta.name }}-redis-metrics'
  namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  type: ClusterIP
  selector:
    plugins.cloudminds.com/loki: loki-redis
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-redis'
  ports:
  - port: 9121
    name: metrics
    protocol: TCP
    targetPort: 9121