apiVersion: v1
kind: Service
metadata:
  name: '{{ansible_operator_meta.name}}-memcached-metrics'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-memcached
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9150
      targetPort: metrics
  selector:
    plugins.cloudminds.com/loki: loki-memcached
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'
