apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: '{{ansible_operator_meta.name}}'-memcached
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-memcached
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'