apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ ansible_operator_meta.name }}-memcached'
  namespace: '{{ ansible_operator_meta.namespace }}'
  labels:
    plugins.cloudminds.com/loki: loki-memcached
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      plugins.cloudminds.com/loki: loki-memcached
      app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'
  endpoints:
    - port: metrics
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: host
  namespaceSelector:
    matchNames: 
    - '{{ ansible_operator_meta.namespace }}'