apiVersion: v1
kind: Service
metadata:
  name: '{{ansible_operator_meta.name}}-memcached'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-memcached
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: memcached
      port: 11211
      targetPort: memcached
      nodePort: null
  selector:
    plugins.cloudminds.com/loki: loki-memcached
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-memcached'