#jinja2:lstrip_blocks: True
apiVersion: v1
kind: Service
metadata:
  name: '{{ansible_operator_meta.name}}-loki-system'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-system
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-system'
  type: ClusterIP
spec:
  ports:
    - name: http-3100
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc-9095
      port: 9095
      protocol: TCP
      targetPort: 9095
    {% if service.mode == "cluster" and service.cluster.ring.type == "memberlist" %}
    - name: tcp-7946
      port: 7946
      protocol: TCP
      targetPort: 7946 
    {% endif %}
  selector:
    plugins.cloudminds.com/loki: loki-system
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-system'
