apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ansible_operator_meta.name}}-loki-system'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-system
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-system'
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      plugins.cloudminds.com/loki: loki-system
      app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-system'
  endpoints:
    - port: http-3100
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: host
  namespaceSelector:
    matchNames:
    - '{{ansible_operator_meta.namespace}}' 