apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ansible_operator_meta.name}}-loki-gateway'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-gateway
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-gateway'
spec:
  replicas: {{ service.cluster.gateway.replicas }}
  selector:
    matchLabels:
      plugins.cloudminds.com/loki: loki-gateway
      app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-gateway'
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        plugins.cloudminds.com/loki: loki-gateway
        app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-gateway'
    spec:
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    plugins.cloudminds.com/loki: loki-gateway
                    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-gateway'
                namespaces:
                  - '{{ansible_operator_meta.namespace}}'
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      containers:
      - image: '{{service.cluster.gateway.image}}:{{service.cluster.gateway.tag}}'
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 3100
          timeoutSeconds: 5
        name: loki-gateway
        ports:
        - containerPort: 3100
          name: http-3100
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: loki-gateway-config
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: '{{ ansible_operator_meta.name }}-loki-gateway-conf'
        name: loki-gateway-config