apiVersion: v1
kind: Service
metadata:
  name: '{{ansible_operator_meta.name}}-loki-gateway'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-gateway
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-gateway'
spec:
  type: NodePort
  ports:
    - name: http-3100
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    plugins.cloudminds.com/loki: loki-gateway
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-gateway'