apiVersion: v1
kind: Service
metadata:
  name: '{{ansible_operator_meta.name}}-loki-frontend'
  namespace: '{{ansible_operator_meta.namespace}}'
  labels:
    plugins.cloudminds.com/loki: loki-frontend
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-frontend'
spec:
  type: ClusterIP
  ports:
  - name: http-3100
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: grpc-9095
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    plugins.cloudminds.com/loki: loki-frontend
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-loki-frontend'
